# Generated by Django 5.2.8 on 2025-11-13 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('default_personality', models.CharField(max_length=30)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('platform_category', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('wearable', 'Wearable'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('speech_patterns', models.JSONField(default=dict, help_text='JSON object with speech characteristics')),
                ('category', models.CharField(choices=[('temperament', 'Temperament'), ('humor', 'Humor Style'), ('communication', 'Communication'), ('attitude', 'Attitude'), ('quirks', 'Quirks')], max_length=20)),
                ('compatible_traits', models.ManyToManyField(blank=True, to='devices.personalitytrait')),
                ('conflicting_traits', models.ManyToManyField(blank=True, related_name='conflicts_with', to='devices.personalitytrait')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('web', 'Web Browser'), ('other', 'Other')], max_length=20)),
                ('device_identifier', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=20)),
                ('personality_type', models.CharField(choices=[('snarky', 'Snarky'), ('logical', 'Logical'), ('chaotic', 'Chaotic'), ('supportive', 'Supportive'), ('dramatic', 'Dramatic'), ('minimalist', 'Minimalist'), ('workaholic', 'Workaholic'), ('social', 'Social Butterfly'), ('creative', 'Creative'), ('anxious', 'Anxious'), ('chill', 'Chill'), ('competitive', 'Competitive')], max_length=30)),
                ('custom_personality_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('data_collection_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_usage', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype')),
                ('personality_traits', models.ManyToManyField(blank=True, to='devices.personalitytrait')),
            ],
            options={
                'ordering': ['-is_primary', '-last_usage', 'name'],
                'unique_together': {('user', 'device_identifier')},
            },
        ),
        migrations.CreateModel(
            name='DeviceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('rivals', 'Rivals'), ('best_friends', 'Best Friends'), ('work_partners', 'Work Partners'), ('siblings', 'Like Siblings'), ('mentor_student', 'Mentor & Student'), ('frenemies', 'Frenemies'), ('ignored', 'Barely Acknowledge Each Other')], max_length=30)),
                ('intensity', models.IntegerField(default=5, help_text='Relationship intensity from 1-10')),
                ('notes', models.TextField(blank=True)),
                ('interactions_count', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='devices.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='devices.device')),
            ],
            options={
                'unique_together': {('device_a', 'device_b')},
            },
        ),
    ]
