from rest_framework import viewsets, filters
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from .models import UserStats, TrendAnalysis
from .serializers import UserStatsSerializer, TrendAnalysisSerializer


class UserStatsViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for user statistics (read-only, generated by tasks)
    """
    serializer_class = UserStatsSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ['date']
    ordering_fields = ['date']
    ordering = ['-date']
    
    def get_queryset(self):
        user = self.request.user
        return UserStats.objects.filter(user=user)
    
    @action(detail=False, methods=['get'])
    def latest(self, request):
        """Get the latest stats"""
        stats = self.get_queryset().first()
        if stats:
            serializer = self.get_serializer(stats)
            return Response(serializer.data)
        return Response({"message": "No stats available yet"})


class TrendAnalysisViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for trend analysis (read-only, generated by tasks)
    """
    serializer_class = TrendAnalysisSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ['period_type']
    ordering_fields = ['start_date']
    ordering = ['-start_date']
    
    def get_queryset(self):
        user = self.request.user
        return TrendAnalysis.objects.filter(user=user)
    
    @action(detail=False, methods=['get'])
    def latest(self, request):
        """Get the latest trend analysis"""
        period_type = request.query_params.get('period_type', 'weekly')
        trend = self.get_queryset().filter(period_type=period_type).first()
        if trend:
            serializer = self.get_serializer(trend)
            return Response(serializer.data)
        return Response({"message": f"No {period_type} trends available yet"})
