# Generated by Django 5.2.8 on 2025-11-13 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('devices', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conversation_type', models.CharField(max_length=30)),
                ('system_prompt', models.TextField(help_text='System prompt for AI')),
                ('user_prompt_template', models.TextField(help_text='User prompt template with placeholders')),
                ('max_participants', models.IntegerField(default=5)),
                ('min_participants', models.IntegerField(default=2)),
                ('preferred_mood', models.CharField(blank=True, max_length=20)),
                ('usage_requirements', models.JSONField(default=dict, help_text='Requirements for using this template')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('usage_threshold', 'Usage Threshold'), ('pattern_detected', 'Pattern Detected'), ('app_milestone', 'App Milestone'), ('time_based', 'Time Based'), ('social_event', 'Social Event'), ('goal_progress', 'Goal Progress'), ('device_event', 'Device Event'), ('manual', 'Manual Trigger')], max_length=30)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met')),
                ('priority', models.IntegerField(default=5, help_text='1-10 priority level')),
                ('cooldown_hours', models.IntegerField(default=24, help_text='Hours before trigger can fire again')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('conversation_type', models.CharField(choices=[('daily_recap', 'Daily Recap'), ('usage_intervention', 'Usage Intervention'), ('pattern_discussion', 'Pattern Discussion'), ('goal_check_in', 'Goal Check-in'), ('app_drama', 'App Drama'), ('device_gossip', 'Device Gossip'), ('productivity_roast', 'Productivity Roast'), ('social_comparison', 'Social Comparison'), ('milestone_celebration', 'Milestone Celebration'), ('friend_visit', 'Friend Device Visit'), ('emergency_meeting', 'Emergency Meeting')], max_length=30)),
                ('content', models.TextField(help_text='The full conversation content')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of conversation')),
                ('mood', models.CharField(choices=[('humorous', 'Humorous'), ('supportive', 'Supportive'), ('dramatic', 'Dramatic'), ('sarcastic', 'Sarcastic'), ('educational', 'Educational'), ('gossipy', 'Gossipy'), ('competitive', 'Competitive'), ('concerned', 'Concerned'), ('celebratory', 'Celebratory'), ('chaotic', 'Chaotic')], default='humorous', max_length=20)),
                ('trigger_data', models.JSONField(default=dict, help_text='Data that triggered this conversation')),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('generation_prompt', models.TextField(blank=True)),
                ('generation_tokens', models.IntegerField(blank=True, null=True)),
                ('generation_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Currently Generating'), ('completed', 'Completed'), ('failed', 'Generation Failed'), ('retry', 'Retry Needed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_devices', models.ManyToManyField(blank=True, to='social.temporarydeviceconnection')),
                ('participating_apps', models.ManyToManyField(blank=True, to='applications.deviceapp')),
                ('participating_devices', models.ManyToManyField(blank=True, to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('triggers', models.ManyToManyField(blank=True, to='conversations.conversationtrigger')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_rating', models.IntegerField(help_text='1-5 accuracy of usage data representation')),
                ('humor_rating', models.IntegerField(help_text='1-5 humor quality')),
                ('personality_rating', models.IntegerField(help_text='1-5 personality consistency')),
                ('overall_rating', models.IntegerField(help_text='1-5 overall satisfaction')),
                ('what_worked', models.TextField(blank=True)),
                ('what_didnt_work', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('feedback_categories', models.JSONField(default=list, help_text='Categories of feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.TextField(help_text="The app's perspective on the day")),
                ('mood', models.CharField(choices=[('satisfied', 'Satisfied'), ('neglected', 'Neglected'), ('overused', 'Overused'), ('appreciated', 'Appreciated'), ('frustrated', 'Frustrated'), ('excited', 'Excited'), ('jealous', 'Jealous'), ('proud', 'Proud'), ('worried', 'Worried'), ('content', 'Content')], max_length=20)),
                ('session_highlights', models.JSONField(default=list, help_text='Highlights from usage sessions')),
                ('user_behavior_notes', models.TextField(blank=True, help_text='Observations about user behavior')),
                ('app_interactions', models.JSONField(default=dict, help_text='Interactions with other apps')),
                ('usage_satisfaction', models.IntegerField(blank=True, help_text='1-10 satisfaction with usage', null=True)),
                ('productivity_contribution', models.IntegerField(blank=True, help_text='1-10 productivity contribution', null=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='applications.deviceapp')),
                ('mentioned_apps', models.ManyToManyField(blank=True, to='applications.deviceapp')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('device_app', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.TextField(help_text="The device's perspective on the day")),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('frustrated', 'Frustrated'), ('proud', 'Proud'), ('tired', 'Tired'), ('excited', 'Excited'), ('confused', 'Confused'), ('satisfied', 'Satisfied'), ('overwhelmed', 'Overwhelmed'), ('bored', 'Bored'), ('grateful', 'Grateful')], max_length=20)),
                ('notable_events', models.JSONField(default=list, help_text='List of notable events')),
                ('insights', models.TextField(blank=True, help_text="Device's insights about usage patterns")),
                ('usage_summary', models.JSONField(default=dict, help_text="Summary of day's usage")),
                ('personality_development', models.TextField(blank=True, help_text='How personality evolved')),
                ('ai_generated', models.BooleanField(default=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='devices.device')),
                ('mentioned_apps', models.ManyToManyField(blank=True, to='applications.deviceapp')),
                ('mentioned_devices', models.ManyToManyField(blank=True, to='devices.device')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
