# Generated by Django 5.2.8 on 2025-11-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('default_personality_traits', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'App Categories',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bundle_id', models.CharField(max_length=200, unique=True)),
                ('ios_bundle_id', models.CharField(blank=True, max_length=200)),
                ('android_package', models.CharField(blank=True, max_length=200)),
                ('windows_exe', models.CharField(blank=True, max_length=200)),
                ('mac_bundle_id', models.CharField(blank=True, max_length=200)),
                ('icon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('default_personality', models.CharField(choices=[('attention_seeking', 'Attention Seeking'), ('workaholic', 'Workaholic'), ('chill', 'Chill'), ('chaotic', 'Chaotic'), ('creative', 'Creative'), ('social', 'Social'), ('analytical', 'Analytical'), ('entertaining', 'Entertaining'), ('productive', 'Productive'), ('addictive', 'Addictive'), ('helpful', 'Helpful'), ('dramatic', 'Dramatic'), ('competitive', 'Competitive'), ('educational', 'Educational'), ('gossip', 'Gossip'), ('minimalist', 'Minimalist')], max_length=30)),
                ('personality_description', models.TextField(blank=True)),
                ('is_social_media', models.BooleanField(default=False)),
                ('is_productivity', models.BooleanField(default=False)),
                ('is_entertainment', models.BooleanField(default=False)),
                ('is_work_related', models.BooleanField(default=False)),
                ('is_game', models.BooleanField(default=False)),
                ('typical_session_length', models.IntegerField(blank=True, help_text='Typical session in minutes', null=True)),
                ('addictive_potential', models.IntegerField(default=5, help_text='Addictive potential 1-10')),
                ('productivity_score', models.IntegerField(default=5, help_text='Productivity score 1-10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='applications.appcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AppPersonalityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('speech_patterns', models.JSONField(default=dict)),
                ('conversation_style', models.CharField(choices=[('talkative', 'Very Talkative'), ('moderate', 'Moderate'), ('quiet', 'Quiet'), ('only_important', 'Only Important Topics')], default='moderate', max_length=30)),
                ('common_phrases', models.JSONField(default=list)),
                ('reaction_triggers', models.JSONField(default=dict)),
                ('suitable_for_categories', models.ManyToManyField(blank=True, to='applications.appcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=100)),
                ('personality_override', models.CharField(blank=True, choices=[('attention_seeking', 'Attention Seeking'), ('workaholic', 'Workaholic'), ('chill', 'Chill'), ('chaotic', 'Chaotic'), ('creative', 'Creative'), ('social', 'Social'), ('analytical', 'Analytical'), ('entertaining', 'Entertaining'), ('productive', 'Productive'), ('addictive', 'Addictive'), ('helpful', 'Helpful'), ('dramatic', 'Dramatic'), ('competitive', 'Competitive'), ('educational', 'Educational'), ('gossip', 'Gossip'), ('minimalist', 'Minimalist')], max_length=30)),
                ('custom_personality_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('first_installed', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('conversation_participation', models.BooleanField(default=True)),
                ('conversation_frequency', models.CharField(choices=[('always', 'Always Participate'), ('significant', 'Only Significant Usage'), ('mentioned', 'Only When Mentioned'), ('never', 'Never Participate')], default='significant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_apps', to='applications.app')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_apps', to='devices.device')),
            ],
            options={
                'ordering': ['-is_favorite', '-last_used', 'app__name'],
                'unique_together': {('device', 'app')},
            },
        ),
        migrations.CreateModel(
            name='AppRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('rivals', 'Rivals'), ('best_friends', 'Best Friends'), ('work_partners', 'Work Partners'), ('frenemies', 'Frenemies'), ('mentor_student', 'Mentor & Student'), ('gossip_buddies', 'Gossip Buddies'), ('competitors', 'Competitors'), ('enablers', 'Enablers'), ('productivity_team', 'Productivity Team'), ('ignore_each_other', 'Ignore Each Other')], max_length=30)),
                ('same_device', models.BooleanField(default=True)),
                ('user_created', models.BooleanField(default=False)),
                ('interactions_count', models.IntegerField(default=0)),
                ('co_usage_frequency', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='applications.deviceapp')),
                ('app_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='applications.deviceapp')),
            ],
            options={
                'unique_together': {('app_a', 'app_b')},
            },
        ),
    ]
