# Generated by Django 5.2.8 on 2025-11-13 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('reduce_total', 'Reduce Total Screen Time'), ('reduce_app', 'Reduce Specific App Usage'), ('increase_productive', 'Increase Productive App Usage'), ('limit_daily', 'Daily Time Limit'), ('digital_sunset', 'Digital Sunset (No Usage After Time)'), ('weekend_detox', 'Weekend Digital Detox'), ('focus_sessions', 'Focus Sessions'), ('app_replacement', 'Replace App with Alternative')], max_length=30)),
                ('target_minutes_daily', models.IntegerField(blank=True, null=True)),
                ('target_sessions_daily', models.IntegerField(blank=True, null=True)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_successful_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.deviceapp')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsagePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('binge_usage', 'Binge Usage'), ('night_owl', 'Night Owl'), ('morning_person', 'Morning Person'), ('weekend_warrior', 'Weekend Warrior'), ('distracted', 'Distracted'), ('doom_scrolling', 'Doom Scrolling'), ('phantom_vibration', 'Phantom Vibration'), ('app_switching', 'App Switching'), ('notification_addiction', 'Notification Addiction')], max_length=30)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0 confidence in pattern')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_observed', models.IntegerField(default=1)),
                ('pattern_data', models.JSONField(default=dict, help_text='Detailed pattern information')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('weekly', 'Weekly'), ('occasional', 'Occasional'), ('rare', 'Rare')], max_length=20)),
                ('strength', models.CharField(choices=[('weak', 'Weak Pattern'), ('moderate', 'Moderate Pattern'), ('strong', 'Strong Pattern'), ('very_strong', 'Very Strong Pattern')], max_length=20)),
                ('impact_on_productivity', models.IntegerField(default=0, help_text='-5 to +5 scale')),
                ('impact_on_wellness', models.IntegerField(default=0, help_text='-5 to +5 scale')),
                ('is_active', models.BooleanField(default=True)),
                ('user_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apps_involved', models.ManyToManyField(blank=True, to='applications.deviceapp')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('launch_count', models.IntegerField(default=0)),
                ('notification_count', models.IntegerField(default=0)),
                ('background_time_minutes', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('longest_session_minutes', models.IntegerField(default=0)),
                ('average_session_minutes', models.FloatField(default=0.0)),
                ('first_launch_time', models.TimeField(blank=True, null=True)),
                ('last_usage_time', models.TimeField(blank=True, null=True)),
                ('peak_usage_hour', models.IntegerField(blank=True, null=True)),
                ('hourly_usage', models.JSONField(default=list, help_text='Array of 24 hourly usage values in minutes')),
                ('scrolled_distance', models.IntegerField(blank=True, help_text='Distance scrolled in pixels', null=True)),
                ('items_viewed', models.IntegerField(blank=True, null=True)),
                ('actions_performed', models.IntegerField(blank=True, null=True)),
                ('usage_context', models.JSONField(default=dict, help_text='Additional context like location, other apps used')),
                ('data_completeness', models.FloatField(default=1.0)),
                ('estimated', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_data', to='applications.deviceapp')),
            ],
            options={
                'ordering': ['-date', '-time_spent_minutes'],
                'unique_together': {('device_app', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_screen_time', models.IntegerField(default=0, help_text='Total screen time in minutes')),
                ('unlock_count', models.IntegerField(default=0)),
                ('pickup_count', models.IntegerField(default=0)),
                ('notification_count', models.IntegerField(default=0)),
                ('first_pickup_time', models.TimeField(blank=True, null=True)),
                ('last_usage_time', models.TimeField(blank=True, null=True)),
                ('longest_session_minutes', models.IntegerField(default=0)),
                ('average_session_minutes', models.FloatField(default=0.0)),
                ('hourly_usage', models.JSONField(default=list, help_text='Array of 24 hourly usage values in minutes')),
                ('battery_start', models.IntegerField(blank=True, null=True)),
                ('battery_end', models.IntegerField(blank=True, null=True)),
                ('charging_time_minutes', models.IntegerField(default=0)),
                ('weekday', models.IntegerField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('data_completeness', models.FloatField(default=1.0, help_text='0.0 to 1.0, how complete is this data')),
                ('collection_method', models.CharField(choices=[('ios_shortcuts', 'iOS Shortcuts'), ('android_service', 'Android Background Service'), ('manual_entry', 'Manual Entry'), ('estimated', 'Estimated Data'), ('api_sync', 'Third-party API Sync')], max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_data', to='devices.device')),
            ],
            options={
                'ordering': ['-date', 'device'],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
