# Generated by Django 5.2.8 on 2025-11-13 14:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('screen_time_trend', models.JSONField(default=dict)),
                ('app_usage_trends', models.JSONField(default=dict)),
                ('category_trends', models.JSONField(default=dict)),
                ('key_insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_screen_time_all_devices', models.DurationField(default=datetime.timedelta)),
                ('total_pickups_all_devices', models.IntegerField(default=0)),
                ('social_media_time', models.DurationField(default=datetime.timedelta)),
                ('productivity_time', models.DurationField(default=datetime.timedelta)),
                ('entertainment_time', models.DurationField(default=datetime.timedelta)),
                ('communication_time', models.DurationField(default=datetime.timedelta)),
                ('screen_time_rank', models.IntegerField(blank=True, null=True)),
                ('productivity_rank', models.IntegerField(blank=True, null=True)),
                ('weekly_trend', models.CharField(blank=True, max_length=20)),
                ('notable_patterns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'total_screen_time_all_devices'], name='analytics_u_date_8b17b2_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
