# Generated by Django 5.2.8 on 2025-11-13 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('trigger_types', models.JSONField(default=list)),
                ('personality_modifiers', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.CharField(max_length=50)),
                ('model_used', models.CharField(max_length=50)),
                ('prompt_used', models.TextField()),
                ('input_data', models.JSONField()),
                ('generated_content', models.TextField()),
                ('generation_time', models.DurationField()),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'created_at'], name='ai_engine_a_content_4e96f2_idx'), models.Index(fields=['model_used', 'success'], name='ai_engine_a_model_u_033d27_idx')],
            },
        ),
    ]
